name: pr-checks

on: workflow_dispatch

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: lint
      run: |
        flake8 src/*.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/*.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: tests with pytest
      run: |
                pytest
    - name: coverage
      run: |
        coverage run -m pytest
        coverage report --fail-under=50